### ISSUE TITLE
pdb to xyxr converstion 

### ISSUE THREAD

**Issue by Donghua-un** [vosslab/vossvolvox#5]
hello, Voss Volume Voxelator users. i have one problem when i try to convert pdb file to xyzr format, Linux giving me this error pdb_to_xyzr comand not found, please let me know were i am doing mistake  
thank you so much

**Comment by vosslab** [comment]
I would need more details to understand the issue, I just merged a pull request that make it so you can run pdb_to_xyzr from and location. My guess is that your system could not find it.
